import { TradeRecommendation, NewsItem, PositionUpdate } from './types';

export const MOCK_RECOMMENDATIONS: TradeRecommendation[] = [
  {
    ticker: 'NVDA',
    direction: 'LONG',
    confidence: 87,
    entryZone: '$127.50 - $128.20',
    stopLoss: '$124.80',
    target: '$134.00',
    timeframe: '2-3 days',
    rationale: 'Strong bullish engulfing candle on above-average volume signals institutional accumulation. Price bounced decisively off the 20-day EMA with momentum building. AI semiconductor demand narrative remains intact as a strong tailwind.',
    pattern: 'Bullish Engulfing + EMA Bounce',
  },
  {
    ticker: 'AMD',
    direction: 'LONG',
    confidence: 79,
    entryZone: '$155.00 - $156.50',
    stopLoss: '$151.20',
    target: '$165.00',
    timeframe: '2-3 days',
    rationale: 'Hammer candle formed at key horizontal support after a 3-day pullback from highs. Volume dried up on the dip suggesting sellers are exhausted. Relative strength vs sector peers remains elevated.',
    pattern: 'Hammer at Support',
  },
  {
    ticker: 'AAPL',
    direction: 'LONG',
    confidence: 72,
    entryZone: '$213.00 - $214.00',
    stopLoss: '$209.50',
    target: '$221.00',
    timeframe: '1-2 days',
    rationale: 'Inside bar consolidation near all-time highs suggests a tight coil before breakout. Volume profile shows strong buying interest. Services growth story provides fundamental support for the move.',
    pattern: 'Inside Bar Consolidation',
  },
  {
    ticker: 'TSLA',
    direction: 'SHORT',
    confidence: 68,
    entryZone: '$248.00 - $250.00',
    stopLoss: '$255.50',
    target: '$235.00',
    timeframe: '2-3 days',
    rationale: 'Shooting star candle at multi-week resistance with significantly above-average volume indicates distribution. Failed breakout above the $250 level on two consecutive attempts. Momentum indicators showing bearish divergence.',
    pattern: 'Shooting Star at Resistance',
  },
  {
    ticker: 'META',
    direction: 'LONG',
    confidence: 81,
    entryZone: '$495.00 - $497.00',
    stopLoss: '$488.00',
    target: '$512.00',
    timeframe: '2-3 days',
    rationale: 'Three white soldiers pattern forming after base consolidation near the 50-day MA. Volume confirmation on each up day shows genuine buying pressure. AI monetization runway supporting bullish thesis.',
    pattern: 'Three White Soldiers',
  },
  {
    ticker: 'MSFT',
    direction: 'LONG',
    confidence: 74,
    entryZone: '$415.00 - $417.00',
    stopLoss: '$410.00',
    target: '$430.00',
    timeframe: '2-3 days',
    rationale: 'Bullish harami pattern after a brief pullback to rising 10-day EMA. Copilot and Azure AI growth providing strong fundamental backdrop. Low implied volatility makes the risk/reward favorable.',
    pattern: 'Bullish Harami',
  },
  {
    ticker: 'SPY',
    direction: 'LONG',
    confidence: 65,
    entryZone: '$525.00 - $526.50',
    stopLoss: '$520.00',
    target: '$535.00',
    timeframe: '1-2 days',
    rationale: 'Doji candle at short-term support signals indecision after the selloff — typically resolves in direction of the primary trend which remains up. Breadth indicators showing oversold bounce setup.',
    pattern: 'Doji at Support',
  },
  {
    ticker: 'GOOGL',
    direction: 'LONG',
    confidence: 70,
    entryZone: '$175.00 - $176.50',
    stopLoss: '$171.00',
    target: '$184.00',
    timeframe: '2-3 days',
    rationale: 'Morning star reversal pattern completed with strong close above the open of the first candle. Search advertising resilience and Gemini AI optionality provide dual catalysts. Institutional buying detected on volume surge.',
    pattern: 'Morning Star Reversal',
  },
  {
    ticker: 'AMZN',
    direction: 'LONG',
    confidence: 76,
    entryZone: '$188.00 - $189.50',
    stopLoss: '$184.00',
    target: '$198.00',
    timeframe: '2-3 days',
    rationale: 'Cup and handle breakout attempt after 5-week consolidation base. AWS margin expansion narrative driving institutional interest. Volume on breakout day exceeded 20-day average by 40%.',
    pattern: 'Cup and Handle Breakout',
  },
  {
    ticker: 'QQQ',
    direction: 'SHORT',
    confidence: 58,
    entryZone: '$455.00 - $456.50',
    stopLoss: '$460.00',
    target: '$445.00',
    timeframe: '1-2 days',
    rationale: 'Evening star pattern at top of recent trading range with volume confirmation. Overbought short-term conditions after 5-day rally. Hedge position against long book — lower conviction than individual names.',
    pattern: 'Evening Star',
  },
];

export const MOCK_NEWS: NewsItem[] = [
  {
    id: '1',
    headline: 'Fed Minutes Signal Caution on Rate Cuts Amid Persistent Inflation',
    summary: 'Federal Reserve officials expressed concern about cutting rates too quickly as inflation remains above target, according to meeting minutes released Wednesday.',
    source: 'Reuters',
    url: '#',
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    symbols: ['SPY', 'QQQ'],
  },
  {
    id: '2',
    headline: 'NVIDIA Unveils Next-Gen Blackwell Ultra GPU Architecture at GTC',
    summary: 'NVIDIA announced its next generation AI chip platform with 2x performance gains over current Blackwell, sending shares to intraday highs.',
    source: 'Bloomberg',
    url: '#',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    symbols: ['NVDA', 'AMD'],
  },
  {
    id: '3',
    headline: "Apple's Services Revenue Hits Record $26B, Beats Estimates",
    summary: "Apple reported record services revenue driven by App Store and Apple TV+ growth, helping offset a slight decline in iPhone unit sales.",
    source: 'CNBC',
    url: '#',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    symbols: ['AAPL'],
  },
  {
    id: '4',
    headline: 'Tesla Deliveries Miss Q1 Estimates by 8%, Shares Drop Pre-Market',
    summary: 'Tesla reported Q1 deliveries of 386,810 vehicles, falling short of analyst expectations of 421,000, citing production retooling at its Fremont factory.',
    source: 'WSJ',
    url: '#',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    symbols: ['TSLA'],
  },
  {
    id: '5',
    headline: "Meta's Llama 4 Surpasses GPT-4o on Multiple Benchmarks",
    summary: "Meta AI's latest open-source model claims top spots on coding and reasoning benchmarks, intensifying competition in the AI model race.",
    source: 'TechCrunch',
    url: '#',
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    symbols: ['META', 'GOOGL', 'MSFT'],
  },
  {
    id: '6',
    headline: 'Amazon Web Services Announces 40% YoY Growth in Cloud Segment',
    summary: 'AWS revenue accelerated to $29.3B quarterly, with management guiding for continued double-digit growth as enterprise AI workloads ramp.',
    source: 'Financial Times',
    url: '#',
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    symbols: ['AMZN'],
  },
  {
    id: '7',
    headline: 'Microsoft Copilot Reaches 1 Million Enterprise Seats, Raises Guidance',
    summary: 'Microsoft reported its AI Copilot assistant crossed 1 million paid enterprise seats, ahead of schedule, as productivity AI adoption accelerates.',
    source: 'Bloomberg',
    url: '#',
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    symbols: ['MSFT'],
  },
];

export const MOCK_POSITION_UPDATE: PositionUpdate = {
  verdict: 'HOLD',
  reasoning: 'Price action remains constructive — consolidating in a tight range just below the target. Volume has declined on the pause, indicating healthy digestion rather than distribution. Original thesis intact; maintain position with stop at entry level.',
  currentPrice: '$129.45',
  priceChange: '+1.52%',
};
